title: Internet Protocols Laboratory
email: colin.perkins@glasgow.ac.uk
description: >-
  The Internet Protocols Laboratory at the University of Glasgow.
  studies the development of the Internet protocols, architecture,
  and technologies.
baseurl: "/"
url: "https://glasgow-ipl.github.io"
domain: glasgow-ipl.github.io
github_username:  csperkins

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
